/*
 * DEVS Streaming Framework Store Java Copyright (C) 2025 simlytics.cloud LLC and
 * DEVS Streaming Framework Store Java contributors.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package devs.msg.mutability;

import devs.Port;
import devs.msg.PortValue;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import org.immutables.value.Value;


/**
 * Represents an immutable implementation of a {@link Port}. This class enforces immutability
 * for the values it handles, ensuring that only objects recognized as immutable or converted
 * into an immutable form are accepted.
 *
 * The immutable nature of this class guarantees that values associated with the port cannot
 * be directly modified after creation, providing a safeguard against unintended state changes.
 *
 * @param <I> the type of data associated with this port
 */
public class ImmutablePort<I> extends Port<I> {

  /**
   * Constructs a Port instance with a specified identifier and associated data type.
   *
   * @param portIdentifier the unique identifier of the port
   */
  public ImmutablePort(String portIdentifier, Class<I> clazz) {
    super(portIdentifier, clazz);
    if (!clazz.isInterface() && !isImmutable(clazz)) {
      throw new IllegalArgumentException("The class " + clazz.getCanonicalName()
       + " must be immutable");
    }
  }

  


  @Override
  public PortValue<I> createPortValue(I value) {
    if (!isImmutable(value.getClass())) {
      throw new IllegalArgumentException("The class " + value.getClass().getCanonicalName()
       + " must be immutable");
    }
    return super.createPortValue(value);
  }




  /**
   * Determines whether a given class is immutable. A class is considered immutable if:
   * - It is a known immutable type (e.g., String, primitive wrappers, enums, etc.).
   * - It is final and its fields are all private and final.
   * - If it has reference fields, their types are also immutable.
   * - It is generated by the Java Immutables framework.
   *
   * @param clazz the class to check for immutability
   * @return true if the class is immutable; false otherwise
   */
  public static boolean isImmutable(Class<?> clazz) {
    // Check if the class implements the Immutable interface
    if (Immutable.class.isAssignableFrom(clazz)) {
      return true;
    }

    // Check if the class is a known immutable type (including Enum, primitive wrappers, etc.)
    if (isKnownImmutable(clazz) || isImmutablesGeneratedClass(clazz)) {
      return true;
    }

    // Check if the class is final
    if (!Modifier.isFinal(clazz.getModifiers())) {
      return false;
    }

    // Check each field
    for (Field field : clazz.getDeclaredFields()) {
      // Field must be private and final
      int modifiers = field.getModifiers();
      if (!Modifier.isPrivate(modifiers) || !Modifier.isFinal(modifiers)) {
        return false;
      }

      // For reference fields, ensure their types are also immutable
      Class<?> fieldType = field.getType();
      if (!fieldType.isPrimitive() && !isKnownImmutable(fieldType)) {
        return false;
      }
    }

    // If all checks pass, the class is considered immutable
    return true;
  }


  /**
   * Determines whether a given class is a known immutable type.
   * A class is considered known immutable if it is one of the following:
   * - A wrapper for a primitive type (e.g., Integer, Double, Boolean, etc.).
   * - The String class.
   * - An enumeration type.
   * - A primitive type.
   * - The Void class.
   *
   * @param clazz the class to check for being a known immutable type
   * @return true if the class is a known immutable type; false otherwise
   */
  private static boolean isKnownImmutable(Class<?> clazz) {
    return clazz.equals(String.class)
        || clazz.equals(Integer.class)
        || clazz.equals(Double.class)
        || clazz.equals(Boolean.class)
        || clazz.equals(Byte.class)
        || clazz.equals(Character.class)
        || clazz.equals(Short.class)
        || clazz.equals(Long.class)
        || clazz.equals(Float.class)
        || clazz.equals(Void.class)
        || clazz.isEnum()
        || clazz.isPrimitive()
        || clazz.isRecord();
  }


  /**
   * Checks if a given class is generated by the Java Immutables framework.
   *
   * @param clazz the class to check
   * @return true if the class is generated by Java Immutables
   */
  public static boolean isImmutablesGeneratedClass(Class<?> clazz) {
    // Check if class name starts with "Immutable"
    if (clazz.getSimpleName().startsWith("Immutable")) {
      return true;
    }

    // Check for the @Value.Immutable annotation on the interface or abstract class
    for (Annotation annotation : clazz.getDeclaredAnnotations()) {
      if (annotation.annotationType().equals(Value.Immutable.class)) {
            return true;
          }
        }

    // Check the superclass or interfaces
    Class<?> superclass = clazz.getSuperclass();
    if (superclass != null && isImmutablesGeneratedClass(superclass)) {
      return true;
    }
    for (Class<?> iface : clazz.getInterfaces()) {
      if (isImmutablesGeneratedClass(iface)) {
        return true;
      }
    }

    return false;
  }

}
