kafka-cluster {
  bootstrap.servers = ""
  security.protocol = SASL_SSL
  sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule   required username=''   password='';"
  sasl.mechanism = PLAIN
}
kafka-readall-consumer: ${pekko.kafka.consumer} {
  kafka-clients {
    bootstrap.servers = ""
    security.protocol = SASL_SSL
    sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule   required username=''   password='';"
    sasl.mechanism = PLAIN
    enable.auto.commit = false
    auto.offset.reset = earliest
  }
}
