pekko {
  log-level = "DEBUG"
  actor {
    serializers {
      jackson-json = "org.apache.pekko.serialization.jackson.JacksonJsonSerializer"
    }
      serialization-bindings {
        "devs.iso.DevsMessage" = jackson-json
        "devs.iso.time.SimTime" = jackson-json
        "example.ExampleGenStoreApp$GenStoreStart" = jackson-json
      }
  }
  serialization.jackson {
    jackson-json {
      serialization-features {
        INDENT_OUTPUT = on
      }
    }
    jackson-modules += "com.fasterxml.jackson.datatype.jdk8.Jdk8Module"
    jackson-modules += "com.fasterxml.jackson.datatype.guava.GuavaModule"
  }
}
